# Generated by Django 6.0.7 on 2026-08-20 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gameplay', '0005_gamesession_current_question'),
        ('quizzes', '0005_quiz_time_limit_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('in_progress', 'В процессе'), ('finished', 'Завершена')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameplay.gamesession')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_rooms', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplayer.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_per_user_room')],
            },
        ),
    ]
