# Generated by Django 6.0.7 on 2026-08-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_gamesession_room'),
        ('multiplayer', '0001_initial'),
        ('quizzes', '0005_quiz_time_limit_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='room',
            name='quiz',
        ),
        migrations.AddField(
            model_name='room',
            name='current_game_session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_rooms', to='gameplay.gamesession'),
        ),
        migrations.AddField(
            model_name='room',
            name='current_quiz',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomplayer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_players', to='multiplayer.room'),
        ),
    ]
