# Generated by Django 6.0.7 on 2026-08-24 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_gamesession_room'),
        ('multiplayer', '0002_remove_room_game_session_remove_room_quiz_and_more'),
        ('quizzes', '0005_quiz_time_limit_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_game_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_rooms', to='gameplay.gamesession'),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_quiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='quizzes.quiz'),
        ),
    ]
