# Generated by Django 6.0.7 on 2026-09-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_seriesrun_gamesession_series_run'),
        ('multiplayer', '0003_alter_room_current_game_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_series_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_rooms', to='gameplay.seriesrun'),
        ),
    ]
