# Generated by Django 6.0.7 on 2026-09-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0004_room_current_series_run'),
        ('quizzes', '0008_remove_quiz_category_remove_quiz_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_quiz',
        ),
        migrations.AddField(
            model_name='room',
            name='current_series',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_selecting', to='quizzes.quizseries'),
        ),
    ]
