# Generated by Django 6.0.7 on 2026-07-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
    ]
