# Generated by Django 6.0.7 on 2026-08-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_answeroption_options_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='audience',
            field=models.CharField(choices=[('common', 'Без классификатора'), ('children', 'Дети'), ('teens', 'Подростки'), ('middle_ages', 'Средние года'), ('elderly', 'Пожилые')], default='common', max_length=20),
        ),
    ]
