# Generated by Django 6.0.7 on 2026-08-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_seconds',
            field=models.IntegerField(default=30),
        ),
    ]
