# Generated by Django 6.0.7 on 2026-09-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_time_limit_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_seconds',
            field=models.IntegerField(default=50),
        ),
    ]
