# Generated by Django 6.0.7 on 2026-09-13 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_round_order_alter_quiz_status_quizseries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AddField(
            model_name='quizseries',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_series', to='quizzes.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizseries',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
