# Generated by Django 6.0.7 on 2026-10-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_quiz_category_remove_quiz_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizseries',
            options={'ordering': ['-created_at']},
        ),
    ]
