# Generated by Django 6.0.7 on 2026-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_alter_quizseries_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points_per_correct',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
