# Generated by Django 6.0.7 on 2026-10-09 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_quiz_points_per_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='points_per_correct',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
