# Generated by Django 6.0.7 on 2026-08-07 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0005_quiz_time_limit_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('solo', 'Одиночная игра'), ('multiplayer', 'Групповая игра')], max_length=50)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('abandoned', 'Заброшена')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gameplay.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(null=True)),
                ('chosen_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_answers', to='quizzes.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_answers', to='quizzes.question')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_answers', to='gameplay.gameparticipant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'question'), name='unique_question_participant')],
            },
        ),
        migrations.AddConstraint(
            model_name='gameparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_session_participant'),
        ),
    ]
