# Generated by Django 6.0.7 on 2026-08-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_gamesession_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparticipant',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
