# Generated by Django 6.0.7 on 2026-08-11 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_gameparticipant_finished_at'),
        ('quizzes', '0005_quiz_time_limit_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('quiz', 'created_by'), name='unique_in_progress_session_per_user_quiz'),
        ),
    ]
