# Generated by Django 6.0.7 on 2026-08-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_gamesession_unique_in_progress_session_per_user_quiz'),
        ('quizzes', '0005_quiz_time_limit_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question'),
        ),
    ]
