# Generated by Django 6.0.7 on 2026-08-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_gamesession_current_question'),
        ('multiplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to='multiplayer.room'),
        ),
    ]
