# Generated by Django 6.0.7 on 2026-09-12 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_gamesession_room'),
        ('multiplayer', '0003_alter_room_current_game_session_and_more'),
        ('quizzes', '0007_quiz_round_order_alter_quiz_status_quizseries_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('solo', 'Одиночная игра'), ('multiplayer', 'Групповая игра')], max_length=50)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('abandoned', 'Заброшена')], default='in_progress', max_length=20)),
                ('current_round_index', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_runs', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_runs', to='multiplayer.room')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='quizzes.quizseries')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='series_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='gameplay.seriesrun'),
        ),
    ]
