# Generated by Django 6.0.7 on 2026-09-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_seriesrun_gamesession_series_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='series_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='gameplay.seriesrun'),
        ),
    ]
