# Generated by Django 6.0.7 on 2026-09-13 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0008_alter_gamesession_series_run'),
        ('multiplayer', '0004_room_current_series_run'),
        ('quizzes', '0008_remove_quiz_category_remove_quiz_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesrun',
            name='current_round_index',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='seriesrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('series', 'created_by'), name='unique_in_progress_session_run_per_user_series'),
        ),
    ]
