# Generated by Django 6.0.7 on 2026-07-24 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('questions', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('common', 'Без уровня'), ('junior', 'Junior'), ('middle', 'Middle'), ('pro', 'Pro')], default='common')),
                ('audience', models.CharField(choices=[('common', 'Без классификатора'), ('children', 'Дети'), ('teens', 'Подростки'), ('middle_ages', 'Средние года'), ('elderly', 'Пожилые')], default='common')),
                ('style', models.CharField(choices=[('serious', 'Серьезный стиль'), ('humorous', 'Шутливый стиль')], default='humorous')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='pending')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_requests', to='quizzes.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
