# Generated by Django 6.0.7 on 2026-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='quiz_status',
            field=models.CharField(choices=[('private', 'Приватный квиз'), ('public', 'Публичный квиз')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='time_limit_seconds',
            field=models.IntegerField(default=50),
        ),
    ]
