# Generated by Django 6.0.7 on 2026-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_generator', '0002_generationrequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='points_per_correct',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
